### Test upload brouillon tiktok

POST https://videoapi.10banc.com/video/tiktok/upload-draft
Content-Type: application/json

{
    "source_info": {
        "source": "PULL_FROM_URL",
        "video_url": "https://videoapi.10banc.com/media/91d49dfd-aff8-4fc8-bb26-b3d504fa1588.mp4"
    }
}