### Test upload brouillon tiktok

POST https://videoapi.10banc.com/video/tiktok/upload-draft
Content-Type: application/json

{
        "video_url": "https://videoapi.10banc.com/media/88f6aea0-17bd-43dc-a9d2-f90553406c9d.mp4"
}

### Test direct post tiktok

POST https://videoapi.10banc.com/video/tiktok/direct-post
Content-Type: application/json

{
        "video_url": "https://videoapi.10banc.com/media/51e85412-8b78-4021-a374-f80bce3de043.mp4"
}

### TEST TIKTOK

### TEST TIKTOK — Vérifier statut du brouillon
POST https://open.tiktokapis.com/v2/post/publish/status/fetch/
Authorization: Bearer act.jlkdYq5zeFysgtnwQjRD05I5bZPeKPUDOZlnj81UjtX3Y4zcq66x96IrV0hh!4864.e1
Content-Type: application/json
Accept: application/json

{
  "publish_id": "v_inbox_url~v2.7560771707275954198"
}

### INFO CREATOR TIKTOK 

POST https://open.tiktokapis.com/v2/post/publish/creator_info/query/
Authorization: Bearer act.jlkdYq5zeFysgtnwQjRD05I5bZPeKPUDOZlnj81UjtX3Y4zcq66x96IrV0hh!4864.e1
Content-Type: application/json; charset=UTF-8

### TEST VIDEO AVEC NOUVEAU PROMPT

POST http://localhost:4000/video/generate
